default:
  api:
  http:
    headers:
      X-Powered-By: Support
      X-Version: 0.0.1
    host: 127.0.0.1
    port: 3000
  imap:
    host: imap.gmail.com
    username: username
    password: password
  nunjucks:
  redis:
    host: 127.0.0.1
    port: 6379
  rethinkdb:
    db: support
    host: 127.0.0.1
    port: 28015
